cabal-version:      2.4
name:               pan-genome
version:            0.1.0.0
author:             avargasta
maintainer:         avargasta@gmail.com
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
  exposed-modules:
       Data.RList
     , Data.ProofCombinators
     , FMIndex.BWT
     , FMIndex.Search
     , FMIndex.Tables
     , FMIndex.Types
     , FMIndex.FMIndex
     , BiIndex.Types
  hs-source-dirs:
      src
  ghc-options:
      -fplugin=LiquidHaskell
  build-depends:
      base >=4.7 && <5
    , containers
    , vector
    , liquid-prelude
    , liquidhaskell
    , liquidhaskell-boot
  default-language: Haskell2010

executable pan-genome
    import:           warnings
    main-is:          Main.hs
    build-depends:    base >=4.7 && <5
    hs-source-dirs:   app
    default-language: Haskell2010
    ghc-options:
      -fplugin=LiquidHaskell
    build-depends:
        base  >=4.7 && <5
      , containers
      , vector
      , pan-genome
      , liquid-prelude
      , liquidhaskell
      , liquidhaskell-boot
    default-language: Haskell2010
